x_offset: 0.03
y_offset: 0.005
z_offset: 0.03
roll_offset: 0
pitch_offset: 0
yaw_offset: 0
hip_pitch_offset: 7.000000052497138
period_time: 4250
dsp_ratio: 0.3
step_forward_back_ratio: 0.28
foot_height: 0.032
swing_right_left: 0.14
swing_top_down: 0
pelvis_offset: 4.99999985454646
arm_swing_gain: 0.2
balance_hip_roll_gain: 0.5
balance_knee_gain: 0.5
balance_ankle_roll_gain: 0.5
balance_ankle_pitch_gain: 0.5
p_gain: 0
i_gain: 0
d_gain: 0